### ISSUE TITLE
Add format verification to the data schema validator

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#260]
**Is your feature request related to a problem? Please describe.**
Add support for `format` checking in the data schema validator. 

**Describe the solution you'd like**
In certain parts of the schema we define a `format` which the expected value should match. 
EG: 
```
        locator:
          type: string
          format: uuid
          example: urn:bjk:hello:asset:c000zk2l88wo
```

**Describe alternatives you've considered**
N/A

**Additional context**
I believe these can be added as and when the schema evolves meaning currently we only need to support `uuid` and `date-time` formats
